import { InventoryDatabase } from '../types/inventory';

export const createEmptyDatabase = (): InventoryDatabase => ({
  types: [],
  groups: [],
  subgroups: [],
  articles: [],
  movements: [],
  version: 1,
  lastUpdated: new Date().toISOString(),
});

/**
 * Dados didáticos representativos de oficinas do SENAI-SP
 * (utilizáveis apenas se o usuário optar por carregar dados de demonstração)
 */
export const createSampleSenaiDatabase = (): InventoryDatabase => {
  const now = new Date().toISOString();
  
  // 1. Tipos
  const tipos = [
    {
      id: 'tip-1',
      code: 'TIP-01',
      name: 'Matéria-Prima e Metais',
      description: 'Aços, alumínios, latões e perfis metálicos para usinagem e serralheria',
      createdAt: now,
    },
    {
      id: 'tip-2',
      code: 'TIP-02',
      name: 'Ferramental e Acessórios',
      description: 'Pastilhas, brocas, machos, fresas e suportes para máquinas-ferramenta',
      createdAt: now,
    },
    {
      id: 'tip-3',
      code: 'TIP-03',
      name: 'Componentes Eletroeletrônicos',
      description: 'Disjuntores, contatores, relés, cabos e sensores para comandos industriais',
      createdAt: now,
    },
    {
      id: 'tip-4',
      code: 'TIP-04',
      name: 'EPI e Segurança do Trabalho',
      description: 'Equipamentos de proteção individual para oficinas e laboratórios industriais',
      createdAt: now,
    },
  ];

  // 2. Grupos
  const grupos = [
    {
      id: 'grp-1',
      tipoId: 'tip-1',
      code: 'GRP-0101',
      name: 'Aços Carbono e Construção Mecânica',
      description: 'Aços SAE 1020, 1045 e tubos estruturais',
      createdAt: now,
    },
    {
      id: 'grp-2',
      tipoId: 'tip-2',
      code: 'GRP-0201',
      name: 'Ferramentas de Corte e Desbaste',
      description: 'Insertos de metal duro e brocas HSS',
      createdAt: now,
    },
    {
      id: 'grp-3',
      tipoId: 'tip-3',
      code: 'GRP-0301',
      name: 'Dispositivos de Manobra e Proteção',
      description: 'Contatores trifásicos e disjuntores-motores',
      createdAt: now,
    },
    {
      id: 'grp-4',
      tipoId: 'tip-4',
      code: 'GRP-0401',
      name: 'Proteção Visual e Auditiva',
      description: 'Óculos de segurança e protetores auriculares tipo concha e plug',
      createdAt: now,
    },
  ];

  // 3. Subgrupos
  const subgrupos = [
    {
      id: 'sub-1',
      tipoId: 'tip-1',
      grupoId: 'grp-1',
      code: 'SUB-010101',
      name: 'Barras Redondas Laminadas / Trefiladas',
      description: 'Tarugos cilíndricos para torno mecânico e CNC',
      createdAt: now,
    },
    {
      id: 'sub-2',
      tipoId: 'tip-2',
      grupoId: 'grp-2',
      code: 'SUB-020101',
      name: 'Insertos Intercambiáveis ISO',
      description: 'Pastilhas de corte revestidas TiAlN',
      createdAt: now,
    },
    {
      id: 'sub-3',
      tipoId: 'tip-3',
      grupoId: 'grp-3',
      code: 'SUB-030101',
      name: 'Contatores de Potência AC-3',
      description: 'Bobinas 24VCC e 220VCA para acionamento de motores',
      createdAt: now,
    },
    {
      id: 'sub-4',
      tipoId: 'tip-4',
      grupoId: 'grp-4',
      code: 'SUB-040101',
      name: 'Óculos de Segurança Policarbonato',
      description: 'Modelos incolor e fumê com proteção UV e antirrisco',
      createdAt: now,
    },
  ];

  // 4. Artigos
  const articles = [
    {
      id: 'art-1',
      tipoId: 'tip-1',
      grupoId: 'grp-1',
      subgrupoId: 'sub-1',
      code: 'ART-010101001',
      name: 'Barra Redonda Aço SAE 1045 Ø 50.8mm (2")',
      description: 'Barra trefilada para exercícios didáticos de torneamento cônico e roscas',
      unit: 'M',
      currentStock: 48,
      minStock: 15,
      maxStock: 80,
      averageCost: 85.50,
      location: {
        warehouse: 'Almoxarifado Central SENAI',
        aisle: 'Rua Metais A',
        shelf: 'Rack Pesado 02',
        bin: 'Nível 1',
        fullAddress: 'Almoxarifado Central SENAI • Rua Metais A • Rack Pesado 02 • Nível 1',
      },
      barcode: '7891000104501',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'art-2',
      tipoId: 'tip-1',
      grupoId: 'grp-1',
      subgrupoId: 'sub-1',
      code: 'ART-010101002',
      name: 'Barra Redonda Aço SAE 1020 Ø 25.4mm (1")',
      description: 'Aço para soldagem e usinagem básica em bancada de ajustagem',
      unit: 'M',
      currentStock: 6,
      minStock: 20, // Crítico!
      maxStock: 100,
      averageCost: 34.20,
      location: {
        warehouse: 'Almoxarifado Central SENAI',
        aisle: 'Rua Metais A',
        shelf: 'Rack Pesado 01',
        bin: 'Nível 2',
        fullAddress: 'Almoxarifado Central SENAI • Rua Metais A • Rack Pesado 01 • Nível 2',
      },
      barcode: '7891000102002',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'art-3',
      tipoId: 'tip-2',
      grupoId: 'grp-2',
      subgrupoId: 'sub-2',
      code: 'ART-020101001',
      name: 'Inserto Metal Duro WNMG 080408-PM',
      description: 'Pastilha trigonal negativa para desbaste e semi-acabamento em aço',
      unit: 'CX',
      currentStock: 25,
      minStock: 10,
      maxStock: 50,
      averageCost: 195.00,
      location: {
        warehouse: 'Oficina de Mecânica de Precisão',
        aisle: 'Armário CNC',
        shelf: 'Gaveteiro Ferramental 03',
        bin: 'Gaveta A-4',
        fullAddress: 'Oficina de Mecânica de Precisão • Armário CNC • Gaveteiro Ferramental 03 • Gaveta A-4',
      },
      barcode: '7892000080408',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'art-4',
      tipoId: 'tip-3',
      grupoId: 'grp-3',
      subgrupoId: 'sub-3',
      code: 'ART-030101001',
      name: 'Contator Tripolar 18A 24VCC (1NA + 1NF)',
      description: 'Contator auxiliar de potência para montagem de painéis didáticos de automação',
      unit: 'UN',
      currentStock: 14,
      minStock: 8,
      maxStock: 30,
      averageCost: 142.80,
      location: {
        warehouse: 'Lab de Comandos Elétricos',
        aisle: 'Bancada 04',
        shelf: 'Armário Componentes',
        bin: 'Box Elétrico 12',
        fullAddress: 'Lab de Comandos Elétricos • Bancada 04 • Armário Componentes • Box Elétrico 12',
      },
      barcode: '7893000018024',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'art-5',
      tipoId: 'tip-4',
      grupoId: 'grp-4',
      subgrupoId: 'sub-4',
      code: 'ART-040101001',
      name: 'Óculos de Proteção Incolor Antirrisco e Antiembaçante',
      description: 'EPI com CA válido para uso obrigatório dos alunos e docentes nas oficinas',
      unit: 'PAR',
      currentStock: 120,
      minStock: 30,
      maxStock: 200,
      averageCost: 12.50,
      location: {
        warehouse: 'Almoxarifado Geral EPIs',
        aisle: 'Corredor Segurança',
        shelf: 'Prateleira 01',
        bin: 'Caixa Plástica Azul 05',
        fullAddress: 'Almoxarifado Geral EPIs • Corredor Segurança • Prateleira 01 • Caixa Plástica Azul 05',
      },
      barcode: '7894000099881',
      createdAt: now,
      updatedAt: now,
    },
  ];

  // 5. Movimentações iniciais didáticas
  const movements = [
    {
      id: 'mov-1',
      articleId: 'art-1',
      articleCode: 'ART-010101001',
      articleName: 'Barra Redonda Aço SAE 1045 Ø 50.8mm (2")',
      type: 'ENTRADA' as const,
      quantity: 50,
      previousStock: 0,
      newStock: 50,
      unitCost: 85.50,
      totalCost: 4275.00,
      documentNumber: 'NF-e 004812',
      partnerOrDepartment: 'Gerdau Aços Especiais S.A.',
      location: articles[0].location,
      responsible: 'Almoxarife Carlos Alberto (SENAI)',
      date: new Date(Date.now() - 5 * 86400000).toISOString(),
      notes: 'Entrada para atendimento ao semestre letivo do curso Técnico de Mecânica',
      createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    },
    {
      id: 'mov-2',
      articleId: 'art-1',
      articleCode: 'ART-010101001',
      articleName: 'Barra Redonda Aço SAE 1045 Ø 50.8mm (2")',
      type: 'SAIDA' as const,
      quantity: 2,
      previousStock: 50,
      newStock: 48,
      unitCost: 85.50,
      totalCost: 171.00,
      documentNumber: 'REQ-MEC-2026/041',
      partnerOrDepartment: 'Oficina de Tornearia - Prof. Roberto (Turma MEC-3A)',
      location: articles[0].location,
      responsible: 'Almoxarife Carlos Alberto (SENAI)',
      date: new Date(Date.now() - 2 * 86400000).toISOString(),
      notes: 'Prática de tornearia mecânica: usinagem de eixos entalhados',
      createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
    {
      id: 'mov-3',
      articleId: 'art-2',
      articleCode: 'ART-010101002',
      articleName: 'Barra Redonda Aço SAE 1020 Ø 25.4mm (1")',
      type: 'ENTRADA' as const,
      quantity: 20,
      previousStock: 0,
      newStock: 20,
      unitCost: 34.20,
      totalCost: 684.00,
      documentNumber: 'NF-e 005119',
      partnerOrDepartment: 'Distribuidora Paulista de Metais',
      location: articles[1].location,
      responsible: 'Almoxarife Carlos Alberto (SENAI)',
      date: new Date(Date.now() - 4 * 86400000).toISOString(),
      notes: 'Lote inicial de aço trefilado para aulas de ajuste mecânico',
      createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    },
    {
      id: 'mov-4',
      articleId: 'art-2',
      articleCode: 'ART-010101002',
      articleName: 'Barra Redonda Aço SAE 1020 Ø 25.4mm (1")',
      type: 'SAIDA' as const,
      quantity: 14,
      previousStock: 20,
      newStock: 6,
      unitCost: 34.20,
      totalCost: 478.80,
      documentNumber: 'REQ-AJUST-2026/088',
      partnerOrDepartment: 'Oficina de Ajustagem - Prof. Marcos',
      location: articles[1].location,
      responsible: 'Almoxarife Carlos Alberto (SENAI)',
      date: new Date(Date.now() - 1 * 86400000).toISOString(),
      notes: 'Usinagem de grampos de fixação pelos alunos do 1º módulo',
      createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    },
    {
      id: 'mov-5',
      articleId: 'art-4',
      articleCode: 'ART-030101001',
      articleName: 'Contator Tripolar 18A 24VCC (1NA + 1NF)',
      type: 'ENTRADA' as const,
      quantity: 14,
      previousStock: 0,
      newStock: 14,
      unitCost: 142.80,
      totalCost: 1999.20,
      documentNumber: 'NF-e 009233',
      partnerOrDepartment: 'WEG Equipamentos Elétricos',
      location: articles[3].location,
      responsible: 'Almoxarife Carlos Alberto (SENAI)',
      date: new Date(Date.now() - 3 * 86400000).toISOString(),
      notes: 'Equipamentos para bancadas do laboratório de eletrotécnica',
      createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    },
  ];

  return {
    types: tipos,
    groups: grupos,
    subgroups: subgrupos,
    articles: articles,
    movements: movements,
    version: 1,
    lastUpdated: now,
  };
};
